// <auto-generated />
namespace ApartmentRentalService.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class sadfgdh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sadfgdh));
        
        string IMigrationMetadata.Id
        {
            get { return "201912212121484_sadfgdh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
